/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/MainGame.ls
 */
export class MainGameRTBase extends Laya.Scene {
    public mainBox!: Laya.Box;
    public readyBox!: Laya.Box;
    public startBtn!: Laya.Button;
    public tips!: Laya.Text;
    public topBox!: Laya.Box;
    public timeTxt!: Laya.Text;
    public showBox!: Laya.Box;
    public show1!: Laya.Box;
    public timeTxt1!: Laya.Text;
    //public tips!: Laya.Text;
    public "tips(1)"!: Laya.Text;
    public "tips(2)"!: Laya.Text;
    public "tips(3)"!: Laya.Text;
    public "timeTxt(1)"!: Laya.Text;
    public show2!: Laya.Box;
    public show3!: Laya.Box;
    //public tips!: Laya.Text;
    //public "tips(1)"!: Laya.Text;
}

